pipeline {
      agent {
        label 'docker' 
    }

    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Clean workspace start') {
            steps {
                cleanWs() 
            }
        }

        stage('Checkout code') {
            steps {
                echo 'Cloning repository'
                git branch: 'main', url: 'https://github.com/Mariia-Fesiun/systems-programming.git'
            }
        }

        stage('Execute script') {
            steps {
                echo 'Running script from lab 3'
                sh 'chmod +x lab3/source_deb/usr/local/bin/script_lab3'
                sh './lab3/source_deb/usr/local/bin/script_lab3'
            }
        }

        stage('Install deb package') {
            steps {
                echo 'Installing deb package'
                sh 'apt-get update'
                sh 'dpkg -i lab3/lab3.deb || apt-get install -f -y'
            }
        }

        stage('Verify installation') {
            steps {
                echo 'Verifying installation'
                sh 'dpkg -l | grep lab3'
            }
        }
    }

    post {
        always {
            cleanWs()
            echo 'Workspace cleaned'
        }
        success {
            echo 'Build successful'
        }
        failure {
            echo 'Build failed'
        }
    }
}